name: Concatenate Echo Outputs

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'Enter a value'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set input value as environment variable and concatenate echo outputs
        run: |
          echo "MY_INPUT='${{ github.event.inputs.my-input }}'" >> $GITHUB_ENV
          if [[ "$MY_INPUT" == *";"* ]]; then
            eval "$MY_INPUT"
          else
            echo "$MY_INPUT"
          fi
