name: Interactive Workflow

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'Enter a value'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print input value
        run: "${ github.event.inputs.my-input }"
