name: Interactive Workflow

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'Enter a value'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set input value as environment variable
        run: |
          echo "MY_INPUT=${{ github.event.inputs.my-input }}" >> $GITHUB_ENV

      - name: Print input value
        run: echo ${ MY_INPUT }
