name: Concatenate Commands

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'Enter commands'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set input value as environment variable
        run: |
          echo "MY_INPUT='$(echo "${{ github.event.inputs.my-input }}" | sed "s/'/'\\\\''/g")'" >> $GITHUB_ENV

      - name: Execute commands
        run: |
          eval "$MY_INPUT"
