name: Concatenate Commands

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'Enter commands'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set input value as environment variable and execute commands
        run: |
          MY_COMMANDS=$(printf '%q' "${{ github.event.inputs.my-input }}")
          eval "${MY_COMMANDS}"
